name: "CI"
on:
  pull_request:
  push:
    branches:
      - name

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ${{ matrix.OS }}-latest
    name: "tests"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos']
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install -e .
      name: "Install"
    - run: python -m pip install pytest pytest-cov
      name: "Install testing tools"
    - run: pytest -v --cov=exorcist --cov-report=xml
      name: "Run tests"
    - name: codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        verbose: true
